//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace UserMaintenance.ServiceProduct {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProduct.IServiceProduct")]
    public interface IServiceProduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/Show", ReplyAction="http://tempuri.org/IServiceProduct/ShowResponse")]
        List<WcfService.Models.Product> Show();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/Show", ReplyAction="http://tempuri.org/IServiceProduct/ShowResponse")]
        System.Threading.Tasks.Task<List<WcfService.Models.Product>> ShowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/ShowId", ReplyAction="http://tempuri.org/IServiceProduct/ShowIdResponse")]
        WcfService.Models.Product ShowId(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/ShowId", ReplyAction="http://tempuri.org/IServiceProduct/ShowIdResponse")]
        System.Threading.Tasks.Task<WcfService.Models.Product> ShowIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/Create", ReplyAction="http://tempuri.org/IServiceProduct/CreateResponse")]
        int Create(WcfService.ModelsDto.ProductCreateDto Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/Create", ReplyAction="http://tempuri.org/IServiceProduct/CreateResponse")]
        System.Threading.Tasks.Task<int> CreateAsync(WcfService.ModelsDto.ProductCreateDto Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/Update", ReplyAction="http://tempuri.org/IServiceProduct/UpdateResponse")]
        int Update(WcfService.Models.Product Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/Update", ReplyAction="http://tempuri.org/IServiceProduct/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(WcfService.Models.Product Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/Delete", ReplyAction="http://tempuri.org/IServiceProduct/DeleteResponse")]
        int Delete(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProduct/Delete", ReplyAction="http://tempuri.org/IServiceProduct/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProductChannel : UserMaintenance.ServiceProduct.IServiceProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProductClient : System.ServiceModel.ClientBase<UserMaintenance.ServiceProduct.IServiceProduct>, UserMaintenance.ServiceProduct.IServiceProduct {
        
        public ServiceProductClient() {
        }
        
        public ServiceProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<WcfService.Models.Product> Show() {
            return base.Channel.Show();
        }
        
        public System.Threading.Tasks.Task<List<WcfService.Models.Product>> ShowAsync() {
            return base.Channel.ShowAsync();
        }
        
        public WcfService.Models.Product ShowId(int Id) {
            return base.Channel.ShowId(Id);
        }
        
        public System.Threading.Tasks.Task<WcfService.Models.Product> ShowIdAsync(int Id) {
            return base.Channel.ShowIdAsync(Id);
        }
        
        public int Create(WcfService.ModelsDto.ProductCreateDto Model) {
            return base.Channel.Create(Model);
        }
        
        public System.Threading.Tasks.Task<int> CreateAsync(WcfService.ModelsDto.ProductCreateDto Model) {
            return base.Channel.CreateAsync(Model);
        }
        
        public int Update(WcfService.Models.Product Model) {
            return base.Channel.Update(Model);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(WcfService.Models.Product Model) {
            return base.Channel.UpdateAsync(Model);
        }
        
        public int Delete(int Id) {
            return base.Channel.Delete(Id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int Id) {
            return base.Channel.DeleteAsync(Id);
        }
    }
}
