//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace UserMaintenance.ServiceInvoiceDetail {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInvoiceDetail.IServiceInvoiceDetail")]
    public interface IServiceInvoiceDetail {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoiceDetail/Show", ReplyAction="http://tempuri.org/IServiceInvoiceDetail/ShowResponse")]
        List<WcfService.Models.InvoiceDetail> Show();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoiceDetail/Show", ReplyAction="http://tempuri.org/IServiceInvoiceDetail/ShowResponse")]
        System.Threading.Tasks.Task<List<WcfService.Models.InvoiceDetail>> ShowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoiceDetail/ShowId", ReplyAction="http://tempuri.org/IServiceInvoiceDetail/ShowIdResponse")]
        List<WcfService.Models.InvoiceDetail> ShowId(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoiceDetail/ShowId", ReplyAction="http://tempuri.org/IServiceInvoiceDetail/ShowIdResponse")]
        System.Threading.Tasks.Task<List<WcfService.Models.InvoiceDetail>> ShowIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoiceDetail/Create", ReplyAction="http://tempuri.org/IServiceInvoiceDetail/CreateResponse")]
        int Create(WcfService.ModelsDto.InvoiceDetailCreateDto Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoiceDetail/Create", ReplyAction="http://tempuri.org/IServiceInvoiceDetail/CreateResponse")]
        System.Threading.Tasks.Task<int> CreateAsync(WcfService.ModelsDto.InvoiceDetailCreateDto Model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceInvoiceDetailChannel : UserMaintenance.ServiceInvoiceDetail.IServiceInvoiceDetail, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceInvoiceDetailClient : System.ServiceModel.ClientBase<UserMaintenance.ServiceInvoiceDetail.IServiceInvoiceDetail>, UserMaintenance.ServiceInvoiceDetail.IServiceInvoiceDetail {
        
        public ServiceInvoiceDetailClient() {
        }
        
        public ServiceInvoiceDetailClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceInvoiceDetailClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceInvoiceDetailClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceInvoiceDetailClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public List<WcfService.Models.InvoiceDetail> Show() {
            return base.Channel.Show();
        }
        
        public System.Threading.Tasks.Task<List<WcfService.Models.InvoiceDetail>> ShowAsync() {
            return base.Channel.ShowAsync();
        }
        
        public List<WcfService.Models.InvoiceDetail> ShowId(int Id) {
            return base.Channel.ShowId(Id);
        }
        
        public System.Threading.Tasks.Task<List<WcfService.Models.InvoiceDetail>> ShowIdAsync(int Id) {
            return base.Channel.ShowIdAsync(Id);
        }
        
        public int Create(WcfService.ModelsDto.InvoiceDetailCreateDto Model) {
            return base.Channel.Create(Model);
        }
        
        public System.Threading.Tasks.Task<int> CreateAsync(WcfService.ModelsDto.InvoiceDetailCreateDto Model) {
            return base.Channel.CreateAsync(Model);
        }
    }
}
