//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace UserMaintenance.ServiceInvoice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInvoice.IServiceInvoice")]
    public interface IServiceInvoice {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoice/Show", ReplyAction="http://tempuri.org/IServiceInvoice/ShowResponse")]
        List<WcfService.Models.Invoice> Show();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoice/Show", ReplyAction="http://tempuri.org/IServiceInvoice/ShowResponse")]
        System.Threading.Tasks.Task<List<WcfService.Models.Invoice>> ShowAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoice/ShowId", ReplyAction="http://tempuri.org/IServiceInvoice/ShowIdResponse")]
        WcfService.Models.Invoice ShowId(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoice/ShowId", ReplyAction="http://tempuri.org/IServiceInvoice/ShowIdResponse")]
        System.Threading.Tasks.Task<WcfService.Models.Invoice> ShowIdAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoice/Create", ReplyAction="http://tempuri.org/IServiceInvoice/CreateResponse")]
        int Create(WcfService.ModelsDto.InvoiceCreateDto Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoice/Create", ReplyAction="http://tempuri.org/IServiceInvoice/CreateResponse")]
        System.Threading.Tasks.Task<int> CreateAsync(WcfService.ModelsDto.InvoiceCreateDto Model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoice/Delete", ReplyAction="http://tempuri.org/IServiceInvoice/DeleteResponse")]
        int Delete(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceInvoice/Delete", ReplyAction="http://tempuri.org/IServiceInvoice/DeleteResponse")]
        System.Threading.Tasks.Task<int> DeleteAsync(int Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceInvoiceChannel : UserMaintenance.ServiceInvoice.IServiceInvoice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceInvoiceClient : System.ServiceModel.ClientBase<UserMaintenance.ServiceInvoice.IServiceInvoice>, UserMaintenance.ServiceInvoice.IServiceInvoice {
        
        public ServiceInvoiceClient() {
        }
        
        public ServiceInvoiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceInvoiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceInvoiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceInvoiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }

        public List<WcfService.Models.Invoice> Show() {
            return base.Channel.Show();
        }
        
        public System.Threading.Tasks.Task<List<WcfService.Models.Invoice>> ShowAsync() {
            return base.Channel.ShowAsync();
        }
        
        public WcfService.Models.Invoice ShowId(int Id) {
            return base.Channel.ShowId(Id);
        }
        
        public System.Threading.Tasks.Task<WcfService.Models.Invoice> ShowIdAsync(int Id) {
            return base.Channel.ShowIdAsync(Id);
        }
        
        public int Create(WcfService.ModelsDto.InvoiceCreateDto Model) {
            return base.Channel.Create(Model);
        }
        
        public System.Threading.Tasks.Task<int> CreateAsync(WcfService.ModelsDto.InvoiceCreateDto Model) {
            return base.Channel.CreateAsync(Model);
        }
        
        public int Delete(int Id) {
            return base.Channel.Delete(Id);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int Id) {
            return base.Channel.DeleteAsync(Id);
        }
    }
}
